---

- name: Install HAProxy
  ansible.builtin.apt:
    pkg:
      - haproxy
    state: latest # noqa package-latest
    update_cache: true

- name: Create HAProxy Config
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart HAProxy
