plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - europe-west1-b
  - europe-west1-c
  - europe-west1-d
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
 - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  # Create groups from GCE labels
  - prefix: label
    key: labels
groups:
  validator: "'validator' in name"
  fullnode: "'fullnode' in name"
  geth: "'geth' in name"
hostnames:
  - name
projects:
  - polygon-060623

auth_kind: serviceaccount
service_account_file: ../terraform/polygon-sa.json

cache: "yes"

filters:
  - "labels.network = polygon-edge"
