- name: Gather facts
  hosts: all
  become: true
  tags:
    - always
  tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:

- name: Install common role
  hosts: all
  become: true
  tags:
    - init
  roles:
    - common

- name: Install rootchain-server role
  hosts: geth
  become: true
  tags:
    - geth
  roles:
    - rootchain-server

- name: Install mounted-storage
  hosts: fullnode:validator
  become: true

  tasks:
    - name: Check if Disk Exists
      ansible.builtin.shell: lsblk "{{ storage_device_location }}"
      ignore_errors: yes  # Ignore errors if the disk doesn't exist
      register: disk_exists

    - name: Run Role if Disk Exists
      include_role:
        name: mounted-storage
      when: disk_exists.rc == 0
  tags:
    - edge

- name: Install edge roles
  hosts: fullnode:validator
  become: true
  tags:
    - edge
  roles:
    - edge

- name: Install haproxy role
  hosts: fullnode:validator
  become: true
  tags:
    - haproxy
  roles:
    - haproxy

